server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: pet-provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    first:
    initial-size: 1
    max-active: 5
    password: root
    url: jdbc:mysql://192.168.1.104:3306/pet?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    jpa:
    database: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml

