server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: pet-web
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
redis:
  host: localhost
  port: 6379
  jedis:
  pool:
    max-idle: 300
    max-active: 600
    max-wait: 300

